### ISSUE TITLE
SPI Exercise question

### ISSUE THREAD

**Issue by halt-hammerzeit** [mquinn/STM32#1]
Hello.
How did you achieve loopback SPI debugging for 6.1?
https://github.com/mquinn/STM32/blob/master/Exercise6-1/spi.c
Author says almost nothing about it.
I could wire output PB15 to input PB14, but then the logic analyser is supposed to be unplugged first.
How did you retain logic analyser while wiring output to input?
Maybe some kind of a self-made Y-splitter is required?

**Comment by halt-hammerzeit** [comment]
Oh, I got it: the discovery board has those pins which are accessible from both sides, so you can wire them both on the top side and on the bottom side.
Man, that wasn't an easy one.

**Comment by halt-hammerzeit** [comment]
Yeah, finally, it works.
The book is great by the way.
@geoffreymbrown

**Comment by mquinn** [comment]
Glad you figured it out Nikolay.

**Comment by geoffreymbrown** [comment]
Congratulations !   I'm glad you've been enjoying the book.  I've been
having my own frustrations with the newer stm32cube  software.  Finally
getting a handle on things and have a bunch of working examples -- usb
vcom. usb ramdisk, usb sd card -- all built with gcc for the f3 discovery
board.   I'll get it posted at some point.

Geoffrey
